Finished up what was leftover from yesterday.
SolaceSamples/solace-samples-mqtt pull request #5
Opened 2016-09-29 21:10 UTC by brandonto

One thing to note is that I have not actually ran the samples yet. The instructions to run the samples are ported from the dev portal and may or may not be outdated.

2016-09-30 02:36 UTC, mdspielman requested changes
A few comment found and tracked as review notes. Also, to build the samples, I believe you'll need to update the "build.gradle" so that the build will output the desired wrapper scripts in ./build/staged/bin

2016-09-30 02:36 UTC, mdspielman commented on docs/_tutorials/persistence-with-queues.md
>  NOTE: If you use the default 'MqttConnectOptions', or set 'MqttConnectOptions.cleanSession' to 'true', as done in the publish/subscribe tutorial, then a Non-Durable (a.k.a. Temporary Endpoint) queue
You're missing the target from the Working with Guaranteed Messages link. Target should be _top.

2016-09-30 02:36 UTC, mdspielman commented on docs/_tutorials/persistence-with-queues.md
>  A topic filter in MQTT differs from a Solace SMF topic subscription. Users can learn more about the differences between the two in the Topic Names and Filters section of [MQTT Specification Conforman
Ditto here. Need target _top

2016-10-03 20:48 UTC, brandonto commented
Made some changes. Let me know if there are any additional changes required.

2016-10-03 21:01 UTC, merged